[package]
name = "download-extract"
version = "0.1.0"
edition = "2021"

[dependencies]
binstalk-downloader = "^0.13"
tokio = { version = "^1.43", features = [
  "rt",
  "sync",
], default-features = false }
reqwest = { version = "^0.12", features = ["json"] }
