name: Test

permissions:
  contents: write

on: [push]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NO_COLOR: "1"

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  bench:
    strategy:
      matrix:
        include:
          - bun: https://github.com/oven-sh/bun/releases/latest/download/bun-darwin-x64.zip
            binstall: https://github.com/cargo-bins/cargo-binstall/releases/download/v1.10.23/cargo-binstall-x86_64-apple-darwin.full.zip
            os: macos-13
          - bun: https://github.com/oven-sh/bun/releases/latest/download/bun-darwin-aarch64.zip
            binstall: https://github.com/cargo-bins/cargo-binstall/releases/download/v1.10.23/cargo-binstall-aarch64-apple-darwin.full.zip
            os: macos-14
          - bun: https://github.com/oven-sh/bun/releases/latest/download/bun-windows-x64.zip
            binstall: https://github.com/cargo-bins/cargo-binstall/releases/download/v1.10.23/cargo-binstall-x86_64-unknown-linux-gnu.full.tgz
            os: windows-latest
          - bun: https://github.com/oven-sh/bun/releases/latest/download/bun-linux-x64-baseline.zip
            binstall: https://github.com/cargo-bins/cargo-binstall/releases/download/v1.10.23/cargo-binstall-x86_64-pc-windows-.full.zip
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    name: bench-${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: install
        run: |
          cargo run
      - name: binstall
        run: |
          cargo run -- ${{ matrix.binstall }} binstall
          ls -lh binstall
      - name: bun
        run: |
          cargo run -- ${{ matrix.bun }} bun
          ls -lh bun
